"""Generate the LaTeX tables whose contents come straight from a report.

A fifty-two row table typed by hand is a transcription error waiting to
happen, and it is the kind of error no reviewer catches and no reader can
detect. So the long paper does not contain that table: it contains an
\\input of a file this script writes from reports/step2c_sessions.json.
Rerun the script and the table is current by construction.

    python tools/make_tables.py --reports reports --out paper/tables

The script writes:

    acquisitions.tex   every one of the 52 units: class, n, out-of-fold
                       recall, seed sd, and median peak-to-floor headroom
    compression.tex    the full 4 by 4 resolution-by-precision grid on the
                       standard split and on held-out 13-48

Numbers are rounded here and nowhere else, and the rounding is stated in
the caption. check_expected.py independently verifies the handful of
figures the surrounding prose quotes, so a bug in this script cannot put a
wrong number in the paper's argument without the checker noticing.
"""
import argparse
import json
import os

CLASS_TEX = {"car": "vehicle", "drone": "drone", "person": "pedestrian"}
ORDER = ["drone", "car", "person"]


def read(reports, name):
    with open(os.path.join(reports, name)) as fh:
        return json.load(fh)


# ------------------------------------------------------- the 52 units

def acquisitions(sess):
    """One row per unit, worst recall first, three classes side by side.

    Side by side rather than stacked because 52 stacked rows cost most of a
    page in single column and the table carries no argument that needs the
    height: it is there so a reader can check any unit. Three panels makes
    it 21 rows, the drone class being the longest.

    Worst-first ordering within each panel is a presentation choice and it
    is the honest one: the paper's claim is about the bottom of the
    distribution, so the rows the claim rests on are the rows the reader
    meets first rather than being buried in an alphabetical list.
    """
    cols = {}
    for cls in ORDER:
        rows = sorted(sess[cls]["sessions"], key=lambda r: r["recall"])
        cells = []
        for r in rows:
            name = "\\texttt{%s}" % r["name"].replace("_", "\\_")
            rec = "%.4f" % r["recall"]
            if r["recall"] < 0.5:                       # the paper's subject
                name, rec = "\\textbf{%s}" % name, "\\textbf{%s}" % rec
            cells.append("%s & %d & %s & %.1f" % (name, r["n"], rec,
                                                  r["ptf_median"]))
        cols[cls] = cells
    tall = max(len(cols[c]) for c in ORDER)

    head = " & ".join(["Acq. & $n$ & Recall & Hd"] * len(ORDER))
    out = ["% GENERATED by tools/make_tables.py. Do not edit by hand.",
           "\\begin{tabular}{@{}" + "rrrr" * len(ORDER) + "@{}}",
           "\\toprule",
           " & ".join("\\multicolumn{4}{c}{%s}" % CLASS_TEX[c]
                      for c in ORDER) + " \\\\",
           "".join("\\cmidrule(lr){%d-%d}" % (4 * i + 1, 4 * i + 4)
                   for i in range(len(ORDER))),
           head + " \\\\", "\\midrule"]
    blank = " & & & "
    for i in range(tall):
        out.append(" & ".join(cols[c][i] if i < len(cols[c]) else blank
                              for c in ORDER) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(out) + "\n"


# ------------------------------------------- resolution by precision

def compression(grid):
    """The 4 by 4 grid, standard split beside held-out 13-48.

    Both halves of the study in one table, because the point of the study
    is the contrast between them: the standard split is flat across almost
    the whole grid while the held-out acquisition is not.
    """
    factors = [1, 2, 4, 8]
    bits = [32, 16, 8, 4]
    out = ["% GENERATED by tools/make_tables.py. Do not edit by hand.",
           "\\begin{tabular}{@{}lrrrrr@{}}", "\\toprule",
           "& & \\multicolumn{2}{c}{Standard split} & "
           "\\multicolumn{2}{c}{Held-out \\texttt{13-48}} \\\\",
           "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
           "Aggregation & Bits & Accuracy & Drone recall & Recall & sd \\\\",
           "\\midrule"]
    for fi, f in enumerate(factors):
        if fi:
            out.append("\\addlinespace[2pt]")
        for b in bits:
            k = "%dx_%dbit" % (f, b)
            if k not in grid["standard"]:
                continue
            s, u = grid["standard"][k], grid["unseen"][k]
            lab = "$%d\\times$" % f if b == bits[0] else ""
            out.append("%s & %d & %.4f & %.4f & %.4f & %.4f \\\\"
                       % (lab, b, s["accuracy"], s["drone_recall"],
                          u["accuracy"], u["accuracy_sd"]))
    out.append("\\bottomrule")
    out.append("\\end{tabular}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--reports", default="reports")
    ap.add_argument("--out", default="paper/tables")
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)

    sess = read(args.reports, "step2c_sessions.json")
    grid = read(args.reports, "step3_grid.json")

    jobs = [("acquisitions.tex", acquisitions(sess)),
            ("compression.tex", compression(grid))]
    for name, body in jobs:
        path = os.path.join(args.out, name)
        with open(path, "w") as fh:
            fh.write(body)
        print("wrote %s  (%d lines)" % (path, body.count("\n")))

    n = sum(len(sess[c]["sessions"]) for c in ORDER)
    print("%d acquisition rows: %s" %
          (n, ", ".join("%s %d" % (c, len(sess[c]["sessions"]))
                        for c in ORDER)))
    if n != 52:
        raise SystemExit("expected 52 units, found %d" % n)


if __name__ == "__main__":
    main()
